# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm8350-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),sm8350-common)

endif
